export Home from './Home';
export Consulting from './Consulting';
export Development from './Development';
export Maintenance from './Maintenance';
export Strategy from './Strategy';
export Subscription from './Subscription';
export Warranty from './Warranty';
export Process from './Process';
export OnDemand from './OnDemand';
